// Generated by gencpp from file rover/GpsCoords.msg
// DO NOT EDIT!


#ifndef ROVER_MESSAGE_GPSCOORDS_H
#define ROVER_MESSAGE_GPSCOORDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rover
{
template <class ContainerAllocator>
struct GpsCoords_
{
  typedef GpsCoords_<ContainerAllocator> Type;

  GpsCoords_()
    : header()
    , lat(0.0)
    , lon(0.0)  {
    }
  GpsCoords_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lat(0.0)
    , lon(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;





  typedef boost::shared_ptr< ::rover::GpsCoords_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover::GpsCoords_<ContainerAllocator> const> ConstPtr;

}; // struct GpsCoords_

typedef ::rover::GpsCoords_<std::allocator<void> > GpsCoords;

typedef boost::shared_ptr< ::rover::GpsCoords > GpsCoordsPtr;
typedef boost::shared_ptr< ::rover::GpsCoords const> GpsCoordsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover::GpsCoords_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover::GpsCoords_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rover::GpsCoords_<ContainerAllocator1> & lhs, const ::rover::GpsCoords_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rover::GpsCoords_<ContainerAllocator1> & lhs, const ::rover::GpsCoords_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rover::GpsCoords_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover::GpsCoords_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover::GpsCoords_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover::GpsCoords_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover::GpsCoords_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover::GpsCoords_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover::GpsCoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47cf9e73769a8bd608378ba8f197aee9";
  }

  static const char* value(const ::rover::GpsCoords_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47cf9e73769a8bd6ULL;
  static const uint64_t static_value2 = 0x08378ba8f197aee9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover::GpsCoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover/GpsCoords";
  }

  static const char* value(const ::rover::GpsCoords_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover::GpsCoords_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 lat\n"
"float64 lon\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rover::GpsCoords_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover::GpsCoords_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lat);
      stream.next(m.lon);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsCoords_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover::GpsCoords_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover::GpsCoords_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MESSAGE_GPSCOORDS_H
